---
- name: Calling apache workflow 
  hosts: prod 
  pre_tasks: 
    - name: Take precheck
      debug:
        msg: "Precheck taken"
  roles:
    - apache 
  tasks:
    - name: Take 
      debug:
        msg: "Task perform using task option."
  post_tasks:
    - name:  validate servers
      debug:
        msg: "validation done"
...
