---
- name: Handler's example - 1st play
  hosts: all 
  vars_files:
     - vars.yaml 
  tasks:
    - name: INstallation process.
      yum:
        name: "{{package_list}}"
        state: present 
      when: 
        - inventory_hostname in groups['web'] 
       # - ansible_default_ipv4.address == "172.25.250.10"
        
      notify:
         - installation complated 


    - name: Start and enable service.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ service_list}}"
      when: 
          - inventory_hostname in groups['web'] 
          #or inventory_hostname in groups['db']
        #  - ansible_default_ipv4.address == "172.25.250.11"
      notify:
         - start_enable_httpd

    - name: Adding firewalld rules
      firewalld:
        service: "{{ item }}"
        immediate: yes
        permanent: yes
        state: enabled
      loop: "{{ rule_list }}" 
      when: inventory_hostname in groups['web']

    - name: index.html deployment.
      copy: 
        content: "This is my web server - {{ inventory_hostname }}"
        dest: /var/www/html/index.html 
      when: inventory_hostname in groups['web']

    - name: Configuration changes.
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf.d/httpd.conf
      when: inventory_hostname in groups['web']
      notify:
         - restart httpd
  handlers:
      - name: restart httpd
        service: 
           name: httpd
           state: restarted

      - name: installation complated
        debug:
          msg: "installation complated"

      - name: start_enable_httpd
        debug:
          msg: "Start and enabled httpd services"
...
