---
- name: User and Group management 
  hosts: other
  vars_files:
     - vars.yml 
  tasks:
     - name: Group Creation.
       group:
         name: "{{ item }}"
         state: present 
       loop: "{{  group_list }}"
    
     - name: User creation.
       user:
         name: "{{ item.user_1}}"
         state: present 
         group: "{{ item.group_1 }}"
       loop: 
          - { user_1: user1 , group_1: unixadm }
          - { user_1: user2 , group_1: unixadm }
          - { user_1: user3 , group_1: middleware }
          - { user_1: user4 , group_1: middleware }
          - { user_1: user5 , group_1: networkadm }
          - { user_1: user6 , group_1: networkadm }
          - { user_1: user7 , group_1: dbadm }
          - { user_1: user8 , group_1: dbadm }
          - { user_1: user9 , group_1: app1_grp }
          - { user_1: user10 , group_1: app1_grp }
          - { user_1: user11 , group_1: app2_grp }
          - { user_1: user12 , group_1: app2_grp }
     
...
