---
- name: root password reset 
  hosts: all
  vars_files:
     - password.yml 
  tasks:
    - name: root password reset 
      user:
        name: root 
        #password: "{{ 'password' | password_hash('sha512') }}"
        #password: "{{ password | password_hash('sha512') }}"
        password: "{{ password | password_hash('sha256') }}"
...
