---
- name: First play - Two tasks, deploying on qcs_dc_labs_bangalore host group.
  hosts: qcs_dc_labs_bangalore
  tasks: 
     - name: Service disabled and stopped
       service:
          name: httpd
          enabled: no
          state: stopped
       ignore_errors: yes

     - name: Package un-installation
       yum: 
          name: httpd
          state: absent
...
